name: Desteste - Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Cluster
    runs-on: deploy
    steps:
      - name: Clonar arquivos do repositório
        uses: actions/checkout@v4

      - name: deploy dos resources
        working-directory: ./.github/deploy
        run: |
          kubectl delete -f resources.yml