name: Teste - Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: deploy
    steps:
      - name: Hello, world
        run: echo hello world!

      - name: get nodes
        run: kubectl get nodes
