name: Teste - Deploy

on:
  workflow_dispatch:
  push:
    branches: 
      - main

jobs:
  deploy:
    name: Deploy to Cluster
    runs-on: deploy
    steps:
      - name: Clonar arquivos do repositório
        uses: actions/checkout@v4
      
      - name: Hello, world
        run: echo hello world!

      - name: Obter nós do cluster kubernetes
        run: kubectl get nodes

      - name: Listar arquivos da pasta atual
        run: ls -la .
