name: Teste - Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Cluster
    runs-on: deploy
    steps:
      - uses: actions/checkout@v4

      - name: deploy resources to kubernetes cluster
        working-directory: ./.github/deploy
        run: |
          kubectl apply -f resources.yml